---
serviceAccount:
  annotations:
    "eks.amazonaws.com/role-arn": "arn:aws:iam::123456789102:role/APP_NAME"

envSecrets:
  secret1:
    name: APP_NAME
    data:
      SECRET_NAME: APP_NAME
      REGION_NAME: us-west-2
      DJANGO_WSGI_MODULE: issuer.wsgi
      PORT: '8121'
      DJANGO_LOG_LEVEL: DEBUG

image:
  repository: "123456789102.dkr.ecr.us-west-2.amazonaws.com/APP_NAME"
  pullPolicy: Always
  tag: "latest"

ingresses:
  ingress1:
    name: APP_NAME
    domains: 
      - company.com
      - dev.company.com
    healthCheckPath: /healthz
    annotations:
      ingress.kubernetes.io/target-node-labels: esk.amazonaws.com/nodegroup=default
    rules:
      - paths:
        - path: /
          name: APP_NAME
          serviceName: APP_NAME-http